### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by kevin-bates** [CODAIT/hadoop-yarn-api-python-client#103]
We should move to use GitHub Actions for our CI.

I took an initial stab at this using the following build.yml file but couldn't get past installation failures relative to Kerberos and ran out of time.  Perhaps someone can pick this up or knows what to do about this.  It's like the python-devel stuff isn't present that must be present on the Travis machines or some additional setup is required.

<details><summary>build.yml</summary>
<p>

```
name: Builds
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      TOX_ENV: py${{ matrix.python-version}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [ '3.5', '3.6', '3.7', '3.8', '3.9' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Install dependencies
      run: |
        pip install --upgrade setuptools pip tox coveralls
        pip freeze
    - name: Run the tests
      run: tox
    - name: Code coverage
      run: coveralls
```
</p>
</details>

<details><summary>build issue</summary>
<p>

```
  ERROR: Command errored out with exit status 1:
   command: /home/runner/work/hadoop-yarn-api-python-client/hadoop-yarn-api-python-client/.tox/python/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a2zk91l8/pykerberos_3d4674fd1bf74198ae84d1dbebc78a44/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a2zk91l8/pykerberos_3d4674fd1bf74198ae84d1dbebc78a44/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-45hdlbzs
       cwd: /tmp/pip-install-a2zk91l8/pykerberos_3d4674fd1bf74198ae84d1dbebc78a44/
  Complete output (14 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'kerberos' extension
  creating build
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/runner/work/hadoop-yarn-api-python-client/hadoop-yarn-api-python-client/.tox/python/include -I/opt/hostedtoolcache/Python/3.8.7/x64/include/python3.8 -c src/kerberos.c -o build/temp.linux-x86_64-3.8/src/kerberos.o
  In file included from src/kerberos.c:19:
  src/kerberosbasic.h:17:10: fatal error: gssapi/gssapi.h: No such file or directory
     17 | #include <gssapi/gssapi.h>
        |          ^~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pykerberos
```
</p>
</details>

Complete logs can be found [here](https://github.com/kevin-bates/hadoop-yarn-api-python-client/actions/runs/603424518).
